### ISSUE TITLE
The method-comment change sample generator.

### ISSUE THREAD

**Issue by pavlov200912** [Tbabm/CUP2#1]
Dear authors.

Thanks for your great work. Recently, we are trying to follow CUP2 and train your model on our dataset. While it seems that you did not provide the method-comment change sample generator (code for matching comment sentences inside one doc). To avoid potential bias, if it’s convenient, could you provide the related code? Thanks a lot. 

Best
Pavlov Ivan.

**Comment by Tbabm** [comment]
Hi @pavlov200912,

I've added the scripts for comment sentence matching in `utils`. Please see `utils.comment.test_javadoc_desc_preprocessor` for the usage example.

Thank you for your attention!
